### PR TITLE
v0.2.0

### PR DESCRIPTION
**Pull request by mobileoverlord**

### CODE REVIEW

**Comment by ConnorRigby** [comment]
I guess not super necessary, but could we look at #38 before releasing?

**Comment by mobileoverlord** [comment]
Sure, I was thinking from the wording that 38 wasn't ready yet?

**Comment by ConnorRigby** [comment]
Ah whoops i forgot to update it. I've been using it since i opened it and it's working great. I'll update

**Comment by mobileoverlord** [comment]
I brought #38 in and rebased this, ready to for review @ConnorRigby

**Pull request merged**
