### PR TITLE
Add note about TLS errors due to poor output

### PR DESCRIPTION
**Pull request by fhunleth**

### CODE REVIEW

**Comment by fhunleth** [comment]
I looked into the log message a bit since I thought that RingLogger was inspecting iodata rather than flattening it to a string. It didn't look like RingLogger was at fault, so I stopped looking.

**Comment by jjcarstens** [comment]
This could also potentially mean that the cert exists in NervesHub, but they are sending the wrong one in their request, correct?

Or also potentially that it was created with a different CA than NervesHub is using?

**Comment by fhunleth** [comment]
Maybe? Isn't that the same thing?

While I know that in theory there are many ways the client-side cert can be rejected, the only one that I've seen so far is that I didn't upload the associated signer cert to NervesHub. I guess that you're saying the problem also could be that you signed the device cert with a different the wrong signing cert and the corrective action would be to try signing it again with the right one?

**Comment by jjcarstens** [comment]
Correct..because that was the case I was running into 🤣. I was including the wrong signing cert on the device and the correct one already existed in NervesHub. So maybe its worth adding a note of "make sure you see the cert in https://www.nerves-hub.org/org/certificates or add it with command." or something like that. Possibly even a note of how they can read the serial of a cert to compare with what's in NervesHub as well

**Comment by fhunleth** [comment]
Updated comment in the minimal possible way for expedience and rebased. I think that I'll need to iterate on this to make it better.

**Pull request merged**
