### PR TITLE
Migrate project to umbrella and split out device channel.

### PR DESCRIPTION
**Pull request by mobileoverlord**
**Why is this happening?**

The goal of this PR is to reorganize the project so we can abstract the device channel code into its own project so it can be deployed to in production as its own service. This is due to how we are launching tasks on AWS Fargate. Fargate tasks can only be bound to a single port and since we need to separate the SSL web traffic from the SSL device traffic they need to run in separate containers.

The apps in the umbrella are
* `nerves_hub` - The main web interface for `nerves-hub.org`.
* `nerves_hub_device` - The device connection interface for `device.nerves-hub.org`. This application enables client ssl and is used to support all device communication over either sockets or rest endpoints.
* `nerves_hub_core` - Shared code, primarily models and ecto repositories.

**Why an umbrella, why not a poncho?**

I admit, I've been caught saying in the past "Umbrellas are broken, use ponchos." and in the context of creating Nerves based projects, this is true. The one thing that umbrellas do well is force a collection of applications to use the same dependencies. Since the `nerves_hub` app and the `nerves_hub_device` app are clustering together in production, locking the dependencies with each other is important.

**Results**

This is the last bit of work necessary to have the production environment fully up and running. In production we are launching two of each of the following containers

`nerves_hub`
`nerves_hub_device`
`nerves_hub_ca`

Here is a break down of the highlights of our production environment.

* Load Balancing
  * Containers are load balanced across different availability zones. 
  * Web traffic SSL is handled by the load balancer
* Blue/Green Deployments
  * New deployment containers are started along side current ones and are only marked active once they pass initial health checks.
  * Bad deployments will not take down the service.
* Redirection
  * `://nerves-hub.org` is redirected to `https://www.nerves-hub.org`
  * The application will force SSL.
* Automation
  * Master commits will execute migrations and seeds and then construct, push, and trigger a deployment. 

It is important to note that the seeds.exs should be written in a way so that it does not fail if a record it is trying to insert already exists.

### CODE REVIEW

**Comment by mobileoverlord** [comment]
This has been rebased and is ready to review

**Comment by jlmcgehee21** [comment]
Did the coverage drop so severely because of a coveralls config?

**Comment by mobileoverlord** [comment]
I admit I do not know how to use coveralls. There might be some config that can be added to improve the results.

**Comment by mobileoverlord** [comment]
Coveralls offers two ways of reporting information for an umbrella app.
`mix coveralls --umbrella` - groups all results together
`mix coveralls` - shows results per app

I ran the per app results locally and received the following results
```
MIX_ENV=test mix coveralls
==> nerves_hub_device
Compiling 1 file (.ex)
==> nerves_hub_core
....................................

Finished in 1.6 seconds
1 doctest, 35 tests, 0 failures

Randomized with seed 440197
----------------
COV    FILE                                        LINES RELEVANT   MISSED
 56.3% ../../test/support/fixtures.ex                181       48       21
  0.0% lib/nerves_hub_core.ex                         18        0        0
 33.3% lib/nerves_hub_core/accounts.ex               293       45       30
  0.0% lib/nerves_hub_core/accounts/invite.ex         27        2        2
100.0% lib/nerves_hub_core/accounts/tenant.ex         31        2        0
100.0% lib/nerves_hub_core/accounts/tenant_key.       28        2        0
 26.3% lib/nerves_hub_core/accounts/user.ex          105       19       14
100.0% lib/nerves_hub_core/application.ex             21        3        0
  0.0% lib/nerves_hub_core/certificate.ex             46       15       15
 20.0% lib/nerves_hub_core/deployments.ex             67        5        4
 71.4% lib/nerves_hub_core/deployments/deployme       85       14        4
 30.0% lib/nerves_hub_core/devices.ex                 68       10        7
100.0% lib/nerves_hub_core/devices/device.ex          57        4        0
 54.2% lib/nerves_hub_core/firmwares.ex              159       24       11
 37.5% lib/nerves_hub_core/firmwares/firmware.e       78        8        5
  0.0% lib/nerves_hub_core/firmwares/upload/fil       32       11       11
  0.0% lib/nerves_hub_core/firmwares/upload/s3.       39        9        9
 66.7% lib/nerves_hub_core/products.ex               123        9        3
100.0% lib/nerves_hub_core/products/product.ex        31        2        0
  0.0% lib/nerves_hub_core/release/tasks.ex           68       23       23
  0.0% lib/nerves_hub_core/repo.ex                    11        0        0
 57.1% test/support/data_case.ex                      53        7        3
  0.0% test/support/fixtures.ex                       99       22       22
[TOTAL]  35.2%
----------------
==> nerves_hub_device
.......

Finished in 0.8 seconds
7 tests, 0 failures

Randomized with seed 440197
----------------
COV    FILE                                        LINES RELEVANT   MISSED
 52.1% ../../test/support/fixtures.ex                181       48       23
  0.0% lib/nerves_hub_device.ex                        9        0        0
  0.0% lib/nerves_hub_device/application.ex           29        4        4
  0.0% lib/nerves_hub_device_web.ex                   71        1        1
 81.8% lib/nerves_hub_device_web/channels/devic      102       11        2
 85.7% lib/nerves_hub_device_web/channels/user_       69        7        1
  0.0% lib/nerves_hub_device_web/endpoint.ex          85        2        2
  0.0% lib/nerves_hub_device_web/gettext.ex           24        0        0
  0.0% lib/nerves_hub_device_web/router.ex            12        1        1
100.0% test/support/channel_case.ex                   37        4        0
[TOTAL]  56.4%
----------------
==> nerves_hub
............................................

Finished in 14.1 seconds
44 tests, 0 failures

Randomized with seed 440197
----------------
COV    FILE                                        LINES RELEVANT   MISSED
100.0% ../../test/support/fixtures.ex                181       48        0
  0.0% lib/nerves_hub.ex                               9        0        0
  0.0% lib/nerves_hub/accounts/email.ex               28        3        3
  0.0% lib/nerves_hub/application.ex                  32        5        5
 76.5% lib/nerves_hub/certificate_authority.ex        57       17        4
  0.0% lib/nerves_hub/mailer.ex                        3        0        0
  0.0% lib/nerves_hub_web.ex                          89        1        1
 84.2% lib/nerves_hub_web/controllers/account_c       81       19        3
  0.0% lib/nerves_hub_web/controllers/api/firmw       39        6        6
  0.0% lib/nerves_hub_web/controllers/dashboard        8        1        1
 83.7% lib/nerves_hub_web/controllers/deploymen      198       43        7
 84.6% lib/nerves_hub_web/controllers/device_co      131       26        4
 69.7% lib/nerves_hub_web/controllers/firmware_      118       33       10
  0.0% lib/nerves_hub_web/controllers/password_       91       16       16
100.0% lib/nerves_hub_web/controllers/product_c       62       19        0
  0.0% lib/nerves_hub_web/controllers/session_c       44        7        7
  0.0% lib/nerves_hub_web/controllers/tenant_co       84       13       13
  0.0% lib/nerves_hub_web/endpoint.ex                 77        2        2
  0.0% lib/nerves_hub_web/gettext.ex                  24        0        0
 50.0% lib/nerves_hub_web/plugs/allow_uninvited       23        4        2
  0.0% lib/nerves_hub_web/plugs/api/authenticat       37        4        4
 60.0% lib/nerves_hub_web/plugs/ensure_logged_i       34        5        2
  0.0% lib/nerves_hub_web/plugs/fetch_deploymen       21        3        3
  0.0% lib/nerves_hub_web/plugs/fetch_device.ex       26        4        4
  0.0% lib/nerves_hub_web/plugs/fetch_firmware.       22        5        5
 75.0% lib/nerves_hub_web/plugs/fetch_product.e       18        4        1
  0.0% lib/nerves_hub_web/plugs/fetch_tenant.ex       30        7        7
 42.9% lib/nerves_hub_web/router.ex                   97       28       16
  0.0% lib/nerves_hub_web/views/account_view.ex        3        0        0
  0.0% lib/nerves_hub_web/views/api/error_view.        3        0        0
  0.0% lib/nerves_hub_web/views/api/firmware_up       13        2        2
  0.0% lib/nerves_hub_web/views/dashboard_view.        3        0        0
 50.0% lib/nerves_hub_web/views/deployment_view       29        6        3
  0.0% lib/nerves_hub_web/views/device_view.ex        35        1        1
  0.0% lib/nerves_hub_web/views/email_view.ex         12        5        5
100.0% lib/nerves_hub_web/views/error_helpers.e       40        5        0
100.0% lib/nerves_hub_web/views/error_view.ex         17        1        0
100.0% lib/nerves_hub_web/views/firmware_view.e        8        2        0
100.0% lib/nerves_hub_web/views/layout_view.ex        17        1        0
  0.0% lib/nerves_hub_web/views/password_reset_        3        0        0
  0.0% lib/nerves_hub_web/views/product_view.ex        3        0        0
  0.0% lib/nerves_hub_web/views/session_view.ex        7        1        1
  0.0% lib/nerves_hub_web/views/tenant_view.ex         3        0        0
100.0% test/support/browser_case.ex                   40        1        0
  0.0% test/support/channel_case.ex                   37        4        4
100.0% test/support/conn_case.ex                      38        4        0
  0.0% test/support/data_case.ex                      53        7        7
[TOTAL]  59.0%
----------------
```

It looks like there is a "lack of coverage" in the `nerves_hub_core` app after splitting them apart. This is probably due to the tests being run in `nerves_hub` were exercising the code paths in `nerves_hub_core` and previously participating in improving the numbers since it recognized that those files were tested.

**Pull request merged**
